export type ContextTemplateArgs = {
  readonly id: string;
  readonly industry: string;
  readonly name: string;
};

export function contextTemplate(args: ContextTemplateArgs): string {
  return `# Context module — ${args.id}
# Generated by \`lokomotif modules new context ${args.industry}/${args.name}\`.
# Replace TODOs with content adapted from real Lokomotif practice — never invent module content.
id: ${args.id}
version: 0.1.0
kind: context
title: "TODO: short human-readable title"
description: "TODO: one-sentence description of the context this module embeds."
industry: ["${args.industry}"]
languages: ["tr", "en"]
owner: lokomotif-core
license: Apache-2.0
source_reference: "TODO: anonymized engagement reference"
body:
  domain:
    tr: "TODO: alanın kısa çerçevesi."
    en: "TODO: short framing of the domain."
  data_boundaries:
    - tr: "TODO: veri sınırı"
      en: "TODO: data boundary"
  regulatory_references:
    - framework: "TODO"
      summary:
        en: "TODO: regulatory summary."
  operating_constraints:
    - tr: "TODO: durumsal limit"
      en: "TODO: situational limit"
`;
}
