export type GuardrailTemplateArgs = {
  readonly id: string;
  readonly industry: string;
  readonly name: string;
};

export function guardrailTemplate(args: GuardrailTemplateArgs): string {
  return `# Guardrail module — ${args.id}
# Generated by \`lokomotif modules new guardrail ${args.industry}/${args.name}\`.
# Replace TODOs with content adapted from real Lokomotif practice — never invent module content.
id: ${args.id}
version: 0.1.0
kind: guardrail
title: "TODO: short human-readable title"
description: "TODO: one-sentence description of what this guardrail prevents."
industry: ["${args.industry}"]
languages: ["tr", "en"]
owner: lokomotif-core
license: Apache-2.0
source_reference: "TODO: anonymized engagement reference"
body:
  forbidden:
    - rule:
        tr: "TODO: yapılmaması gereken eylem."
        en: "TODO: forbidden behavior."
      rationale:
        en: "TODO: why this rule exists."
  required_actions:
    - en: "TODO: action the model must take when uncertain."
  escalation:
    en: "TODO: who or where to defer to."
  audit_requirements:
    - en: "TODO: what must be logged or surfaced."
  severity: high
`;
}
