export type RoleTemplateArgs = {
  readonly id: string;
  readonly industry: string;
  readonly name: string;
};

export function roleTemplate(args: RoleTemplateArgs): string {
  return `# Role module — ${args.id}
# Generated by \`lokomotif modules new role ${args.industry}/${args.name}\`.
# Replace TODOs with content adapted from real Lokomotif practice — never invent module content.
id: ${args.id}
version: 0.1.0
kind: role
title: "TODO: short human-readable title"
description: "TODO: one-sentence description of what this role does."
industry: ["${args.industry}"]
languages: ["tr", "en"]
owner: lokomotif-core
license: Apache-2.0
source_reference: "TODO: anonymized engagement reference"
body:
  identity:
    tr: "TODO: kıdemli pratisyen kimliği — Türkçe."
    en: "TODO: senior-practitioner identity — English."
  expertise:
    - tr: "TODO: uzmanlık alanı"
      en: "TODO: domain area"
  perspective:
    tr: "TODO: bakış açısı (opsiyonel)"
    en: "TODO: perspective (optional)"
`;
}
