export type StyleTemplateArgs = {
  readonly id: string;
  readonly industry: string;
  readonly name: string;
};

export function styleTemplate(args: StyleTemplateArgs): string {
  return `# Style module — ${args.id}
# Generated by \`lokomotif modules new style ${args.industry}/${args.name}\`.
# Replace TODOs with content adapted from real Lokomotif practice — never invent module content.
id: ${args.id}
version: 0.1.0
kind: style
title: "TODO: short human-readable title"
description: "TODO: one-sentence description of the style this module enforces."
industry: ["${args.industry}"]
languages: ["tr", "en"]
owner: lokomotif-core
license: Apache-2.0
source_reference: "TODO: anonymized engagement reference"
body:
  voice:
    tr: "TODO: ses ve register tarifi."
    en: "TODO: voice and register description."
  audience:
    tr: "TODO: hedef kitle."
    en: "TODO: target audience."
  register: professional
  examples:
    - en: "TODO: short on-voice example."
  avoid:
    - en: "TODO: phrase or pattern to avoid."
`;
}
