export type TaskTemplateArgs = {
  readonly id: string;
  readonly industry: string;
  readonly name: string;
};

export function taskTemplate(args: TaskTemplateArgs): string {
  return `# Task module — ${args.id}
# Generated by \`lokomotif modules new task ${args.industry}/${args.name}\`.
# Replace TODOs with content adapted from real Lokomotif practice — never invent module content.
id: ${args.id}
version: 0.1.0
kind: task
title: "TODO: short human-readable title"
description: "TODO: one-sentence description of what this task does."
industry: ["${args.industry}"]
languages: ["tr", "en"]
owner: lokomotif-core
license: Apache-2.0
source_reference: "TODO: anonymized engagement reference"
body:
  instructions:
    tr: "TODO: görev talimatları — Türkçe."
    en: "TODO: task instructions — English."
  output_format:
    type: structured
    description:
      tr: "TODO: çıktı yapısı tanımı."
      en: "TODO: output structure description."
  constraints:
    - tr: "TODO: zorunlu kısıt"
      en: "TODO: hard constraint"
`;
}
